version: "3.9"

services:
  fz-eureka-server:
    image: maven:3.9.2-jdk-21
    container_name: fz-eureka-server
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "7070:7070"
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}
    command: >
      /bin/sh -c "mvn clean package -DskipTests &&
                  java -jar target/fz-eureka-server-0.0.1-SNAPSHOT.jar"
