version: "3.9"

services:
  eurekaserver:
    container_name: eurekaserver
    image: eurekaserver:latest
    ports:
      - "7070:7070"
    environment:
      SPRING_APPLICATION_NAME: eurekaserver
      SERVER_PORT: 7070

      EUREKA_CLIENT_FETCH_REGISTRY: "false"
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"

      EUREKA_INSTANCE_HOSTNAME: eurekaserver
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:7070/eureka/
    networks:
      - fz-network
    restart: unless-stopped

networks:
  fz-network:
    driver: bridge
