version: "3.9"

services:
  app:
    build: .
    container_name: fz-eureka-server
    ports:
      - "7070:7070"
    environment:
      SPRING_APPLICATION_NAME: eurekaserver
      SPRING_PROFILES_ACTIVE: prod

      SERVER_PORT: 7070

      EUREKA_CLIENT_FETCH_REGISTRY: "false"
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"

      EUREKA_INSTANCE_HOSTNAME: fz-eureka-server
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://fz-eureka-server:7070/eureka/
    restart: unless-stopped
