version: "3.9"

services:
  build-app:
    image: maven:3.9.2
    container_name: fz-eureka-server
    working_dir: /app
    volumes:
      - ./:/app
    command: mvn clean package -DskipTests

  fz-eureka-server:
    image: eclipse-temurin:21-jre
    container_name: fz-eureka-server
    ports:
      - "7070:7070"
    depends_on:
      - build-app
    volumes:
      - ./target/fz-eureka-server-0.0.1-SNAPSHOT.jar:/app/app.jar
    working_dir: /app
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-prod}
    command: ["java", "-jar", "app.jar"]
