spring :
   application :
     name : eurekaserver

server :
   port : 7070	

eureka :
  client:
    fetch-registry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname : localhost
